/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion.fisioterapia.brazo;

/**
 *
 * @author ild_37
 */
public class Vista extends javax.swing.JFrame {
/**
     Clase Vista
     */
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EstadoLabel = new javax.swing.JLabel();
        PanelBotonera = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AFisioB");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        EstadoLabel.setText("jLabel2");
        getContentPane().add(EstadoLabel, java.awt.BorderLayout.PAGE_END);

        PanelBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevo.setText("NUEVO");
        PanelBotonera.add(btnNuevo);

        btnAbrir.setText("ABRIR");
        PanelBotonera.add(btnAbrir);

        btnSalir.setText("SALIR");
        PanelBotonera.add(btnSalir);

        btnGuardar.setText("Guardar");
        PanelBotonera.add(btnGuardar);

        getContentPane().add(PanelBotonera, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JPanel PanelBotonera;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
