/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion.fisioterapia.brazo;

/**
 *
 * @author ild_37
 */
public class Vista extends javax.swing.JFrame {
/**
     Clase Vista
     */
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EstadoLabel = new javax.swing.JLabel();
        PanelBotonera = new javax.swing.JPanel();
        btnNuevoILD = new javax.swing.JButton();
        btnAbrirILD = new javax.swing.JButton();
        btnGuardarILD = new javax.swing.JButton();
        btnSalirILD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AFisioB");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        EstadoLabel.setText("La vida Dura");
        getContentPane().add(EstadoLabel, java.awt.BorderLayout.PAGE_END);

        PanelBotonera.setBackground(new java.awt.Color(255, 204, 255));
        PanelBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevoILD.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevoILD.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoILD.setText("Nuevo");
        btnNuevoILD.setOpaque(true);
        PanelBotonera.add(btnNuevoILD);

        btnAbrirILD.setBackground(new java.awt.Color(204, 204, 255));
        btnAbrirILD.setForeground(new java.awt.Color(0, 0, 0));
        btnAbrirILD.setText("Abrir");
        btnAbrirILD.setOpaque(true);
        PanelBotonera.add(btnAbrirILD);

        btnGuardarILD.setBackground(new java.awt.Color(204, 204, 255));
        btnGuardarILD.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarILD.setText("Guardar");
        btnGuardarILD.setOpaque(true);
        PanelBotonera.add(btnGuardarILD);

        btnSalirILD.setBackground(new java.awt.Color(204, 204, 255));
        btnSalirILD.setForeground(new java.awt.Color(0, 0, 0));
        btnSalirILD.setText("Salir");
        btnSalirILD.setOpaque(true);
        PanelBotonera.add(btnSalirILD);

        getContentPane().add(PanelBotonera, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JPanel PanelBotonera;
    private javax.swing.JButton btnAbrirILD;
    private javax.swing.JButton btnGuardarILD;
    private javax.swing.JButton btnNuevoILD;
    private javax.swing.JButton btnSalirILD;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
